apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: migration-onboarding-events
  labels:
    strimzi.io/cluster: migration-onboarding
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: migration-onboarding-admin
  labels:
    strimzi.io/cluster: migration-onboarding
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour