apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        tier: backend
    spec:
      containers:
        - name: postgres
          image: postgres:14.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo ok"
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo ok"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tf-postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tf-postgres-credentials
                  key: password
            - name: PGDATA
              value: /postgres/data/pgdata
            - name: POSTGRES_DB
              value: migration-onboarding
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data-volume
              mountPath: /postgres/data
            - name: config-volume
              mountPath: /var/run/postgresql
          resources:
            requests:
              cpu: 1000m
              memory: 320Mi
            limits:
              memory: 1024Mi
      volumes:
        - name: postgres-data-volume
          emptyDir: {}
        - name: config-volume
          emptyDir: {}
