apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        tier: backend
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo ok"
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo ok"
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tf-mysql-credentials
                  key: mysql_root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: tf-mysql-credentials
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tf-mysql-credentials
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: webdam-migrations
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true
          resources:
            requests:
              cpu: 500m
              memory: 320Mi
            limits:
              memory: 1024Mi
      volumes:
        - name: webdam-migrations
          configMap:
            name: webdam-migrations
            optional: true
